#QtumClient Configuration
qtumClient:
  url: http://49.232.209.145:8081/
  username: test
  password: test1234

#MySql configuration
spring:
  datasource:
    url: jdbc:mysql://82.157.174.79:3306/movie_nft
    username: root
    password: Qtum2021#
    driver-class-name: com.mysql.cj.jdbc.Driver

#Server Configuration
server:
  port: 8081

#Log Configuration
logging:
  config: classpath:log4j2.yaml
  level:
    org.springframework.web: INFO
    com.pku.ss.movienftserver: INFO

#FileStorage Configuration
fileStorage:
  path: /usr/share/file/
